import 'dart:typed_data';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fpdart/fpdart.dart';
import 'package:proper_store_shared/models/product_model.dart';

import '../../../../core/failures/app_failures.dart';

abstract interface class ProductsRepo {
  /// Returns a new unique product ID generated by the data layer.
  Future<String> generateProductId();

  Future<Either<ServerFailure, (List<ProductModel>, DocumentSnapshot?)>>
  getAllProducts({DocumentSnapshot? startAfter, required int pageSize});

  Future<Either<ServerFailure, List<ProductModel>>> searchProducts({
    required String query,
  });

  Future<Either<ServerFailure, void>> addProduct({
    required ProductModel product,
  });

  Future<Either<ServerFailure, void>> updateProduct({
    required ProductModel product,
  });

  Future<Either<ServerFailure, void>> deleteProduct({required String id});

  Future<Either<ServerFailure, Unit>> deleteProductImage({required String url});

  Future<Either<ServerFailure, String>> uploadMainProductImage({
    required String productId,
    required Uint8List compressedImage,
  });

  Future<Either<ServerFailure, String>> uploadProductVariantImage({
    required String productId,
    required String colorHex,
    required int index,
    required Uint8List compressedImage,
  });

  Future<Either<ServerFailure, String>> uploadCategoryImage({
    required String categoryName,
    required Uint8List compressedImage,
  });

  Future<Either<ServerFailure, List<ProductModel>>> getProductsByIds(
    List<String> ids,
  );

  Future<Either<ServerFailure, List<String>>> getCategories();

  Future<Either<ServerFailure, Unit>> addCategory({
    required String name,
    required String imageUrl,
  });
}
