// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBubU0hi2FzjRVLR6deBSfHkUayFr3WihM',
    appId: '1:968085072868:web:c8bf02111e2bcf385cf5f1',
    messagingSenderId: '968085072868',
    projectId: 'proper-store-eg',
    authDomain: 'proper-store-eg.firebaseapp.com',
    storageBucket: 'proper-store-eg.firebasestorage.app',
    measurementId: 'G-S4X9PGLK2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmc4g8_4oVIOx2ZZ4ahR57nomkU06FJeo',
    appId: '1:968085072868:android:ea835052dc125cd65cf5f1',
    messagingSenderId: '968085072868',
    projectId: 'proper-store-eg',
    storageBucket: 'proper-store-eg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABXJnDSjCSswX9nPhtRYkyWNjJH5zMn4U',
    appId: '1:968085072868:ios:3cd71855690b94635cf5f1',
    messagingSenderId: '968085072868',
    projectId: 'proper-store-eg',
    storageBucket: 'proper-store-eg.firebasestorage.app',
    iosBundleId: 'com.example.properStore',
  );

}