// Mocks generated by Mockito 5.4.6 from annotations
// in proper_store/test/features/addresses/domain/use_cases/addresses_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:proper_store/core/failures/app_failures.dart' as _i5;
import 'package:proper_store/features/addresses/domain/repo/addresses_repo.dart'
    as _i2;
import 'package:proper_store_shared/models/address_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AddressesRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressesRepo extends _i1.Mock implements _i2.AddressesRepo {
  MockAddressesRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ServerFailure, List<_i6.AddressModel>>>
  getAddresses({required String? customerId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, [], {#customerId: customerId}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ServerFailure, List<_i6.AddressModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ServerFailure, List<_i6.AddressModel>>
                  >(
                    this,
                    Invocation.method(#getAddresses, [], {
                      #customerId: customerId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ServerFailure, List<_i6.AddressModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.ServerFailure, void>> addAddress({
    required String? customerId,
    required _i6.AddressModel? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [], {
              #customerId: customerId,
              #address: address,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ServerFailure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.ServerFailure, void>>(
                this,
                Invocation.method(#addAddress, [], {
                  #customerId: customerId,
                  #address: address,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ServerFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.ServerFailure, void>> deleteAddress({
    required String? customerId,
    required _i6.AddressModel? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [], {
              #customerId: customerId,
              #address: address,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ServerFailure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.ServerFailure, void>>(
                this,
                Invocation.method(#deleteAddress, [], {
                  #customerId: customerId,
                  #address: address,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ServerFailure, void>>);
}
