// Mocks generated by Mockito 5.4.6 from annotations
// in proper_store/test/features/cart/presentation/cubit/cart_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:proper_store/core/failures/app_failures.dart' as _i6;
import 'package:proper_store/features/cart/domain/repo/cart_repo.dart' as _i2;
import 'package:proper_store/features/cart/domain/use_cases/load_cart_items_use_case.dart'
    as _i3;
import 'package:proper_store/features/cart/domain/use_cases/save_cart_items_use_case.dart'
    as _i9;
import 'package:proper_store_shared/models/cart_item_model.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCartRepo_0 extends _i1.SmartFake implements _i2.CartRepo {
  _FakeCartRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoadCartItemsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadCartItemsUseCase extends _i1.Mock
    implements _i3.LoadCartItemsUseCase {
  MockLoadCartItemsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepo get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeCartRepo_0(this, Invocation.getter(#repo)),
          )
          as _i2.CartRepo);

  @override
  _i4.Future<_i5.Either<_i6.ServerFailure, List<_i7.CartItemModel>>> call({
    required String? customerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#customerId: customerId}),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.ServerFailure, List<_i7.CartItemModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.ServerFailure, List<_i7.CartItemModel>>
                  >(
                    this,
                    Invocation.method(#call, [], {#customerId: customerId}),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.ServerFailure, List<_i7.CartItemModel>>
          >);
}

/// A class which mocks [SaveCartItemsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveCartItemsUseCase extends _i1.Mock
    implements _i9.SaveCartItemsUseCase {
  MockSaveCartItemsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepo get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeCartRepo_0(this, Invocation.getter(#repo)),
          )
          as _i2.CartRepo);

  @override
  _i4.Future<_i5.Either<_i6.ServerFailure, void>> call({
    required String? customerId,
    required List<_i7.CartItemModel>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #customerId: customerId,
              #items: items,
            }),
            returnValue: _i4.Future<_i5.Either<_i6.ServerFailure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.ServerFailure, void>>(
                this,
                Invocation.method(#call, [], {
                  #customerId: customerId,
                  #items: items,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.ServerFailure, void>>);
}
